

SELECT * FROM Employee;

SELECT SUM(SALARY) AS TOTAL_SALARY FROM Employee;

SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM Employee;

SELECT MIN(SALARY) AS MINIMUM_SALARY FROM Employee;

SELECT AVG(SALARY) AS AVERAGE_OF_SALARY FROM Employee;

SELECT COUNT(SALARY) AS COUNT_OF_SALARY FROM Employee;


SELECT SUM(SALARY) AS SALARY,Position FROM EMPLOYEE
GROUP BY Position;


INSERT INTO EMPLOYEE VALUES(6,'NEERAJ','GUPTA','QA Engineer','2022-01-15',67999.98);

INSERT INTO EMPLOYEE VALUES(7,'PANKAJ','SINGH','DESIGNER','2021-07-30',67999.00);

INSERT INTO EMPLOYEE VALUES(8,'NAREDRA','MODI','MANAGER','2023-03-22',68000.55);

INSERT INTO EMPLOYEE VALUES(9,'NEERAJ','GUPTA','QA Engineer','2019-05-14',67999.00);

INSERT INTO EMPLOYEE VALUES(10,'NEERAJ','GUPTA','Manager','2019-05-14',67999.00);


SELECT * FROM Employee;



SELECT SUM(SALARY) AS SALARY,COUNT(Salary) AS COUNT_OF, Position,HireDate FROM EMPLOYEE
GROUP BY Position,HireDate;



--------------------------------------------------------HAVING CLAUSE ---------------------------------------------------


SELECT SUM(SALARY) AS SALARY,Position FROM EMPLOYEE
GROUP BY Position HAVING SUM(Salary)>=139000;


SELECT SUM(SALARY) AS SALARY,COUNT(Salary) AS COUNT_OF, Position,HireDate FROM EMPLOYEE
GROUP BY Position,HireDate HAVING SUM(Salary)>=65000;

SELECT SUM(SALARY) AS SALARY,COUNT(Salary) AS COUNT_OF,HireDate,Position FROM EMPLOYEE
GROUP BY HireDate,Position HAVING Position IN('QA ENGINEER');


SELECT SUM(SALARY) AS SALARY,COUNT(Salary) AS COUNT_OF,HireDate,Position FROM EMPLOYEE
GROUP BY HireDate,Position HAVING Position IN('DEVELOPER');


SELECT SUM(SALARY) AS SALARY,COUNT(Salary) AS COUNT_OF,HireDate,Position FROM EMPLOYEE
GROUP BY HireDate,Position HAVING Position IN('MANAGER');

SELECT SUM(SALARY) AS TOTAL_SALARY,Position,HireDate FROM Employee WHERE Position IN('MANAGER','DESIGNER')
GROUP BY Position,HireDate HAVING SUM(Salary)> 65000;


CREATE TABLE PRODUCT_SALES(
PRODUCT_ID INT IDENTITY(1,1),
PRODUCT_NAME VARCHAR(50),
SALES_AMOUNT INT,
);

INSERT INTO PRODUCT_SALES VALUES('MONITOR',1000),
('MOUSE',400),
('HARDISK',600),
('KEYBOARD',300),
('HARDISK',600),
('MONITOR',1000),
('MOUSE',400),
('HARDISK',600),
('MOUSE',400),
('MONITOR',1000),
('HARDISK',600);

DELETE FROM PRODUCT_SALES WHERE PRODUCT_ID=5;

SELECT * FROM PRODUCT_SALES;

TRUNCATE TABLE PRODUCT_SALES;


SELECT PRODUCT_NAME,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM PRODUCT_SALES
WHERE PRODUCT_NAME NOT IN('HARDISK')
GROUP BY PRODUCT_NAME;



SELECT PRODUCT_NAME,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM PRODUCT_SALES
GROUP BY PRODUCT_NAME
HAVING PRODUCT_NAME NOT IN('HARDISK');



SELECT PRODUCT_NAME,SUM(SALES_AMOUNT) AS TOTAL_SALES FROM PRODUCT_SALES
WHERE PRODUCT_NAME NOT IN('HARDISK')
GROUP BY PRODUCT_NAME
HAVING SUM(SALES_AMOUNT) > 1000;

----------------------------------------------------ORDER BY--------------------------------------------------------------------

SELECT * FROM PRODUCT_SALES 
ORDER BY PRODUCT_NAME;


SELECT * FROM PRODUCT_SALES 
ORDER BY PRODUCT_NAME DESC;



SELECT * FROM PRODUCT_SALES 
ORDER BY PRODUCT_NAME ASC;
