CREATE SCHEMA REFERENTIAL_INTEGRITY;

Create Table REFERENTIAL_INTEGRITY.Customer_tbl(
c_id int primary key,
c_name varchar(50),
c_address varchar(50),
city varchar(50));



Insert into REFERENTIAL_INTEGRITY.Customer_tbl Values(1,'NEERAJ','KALYAN','MAHARASHTRA');

Insert into REFERENTIAL_INTEGRITY.Customer_tbl Values(2,'RAMESH','KALYAN','HYDERABAD'),
(3,'MANISH','SATARA','HYDERABAD'),
(4,'SATYANSH','KATIPURA','KOLKATA'),
(5,'VAIBHAV','KANPUR','UTTER PRADESH'),
(6,'AMAN','BANGOLARE','HYDERABAD');

CREATE  TABLE REFERENTIAL_INTEGRITY.ORDER_TBL(
ORD_ID INT PRIMARY KEY,
ITEM VARCHAR(50),
QUANTITY INT,
PRICE_OF_1 INT,
C_ID INT FOREIGN KEY REFERENCES REFERENTIAL_INTEGRITY.CUSTOMER_TBL(C_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO  REFERENTIAL_INTEGRITY.ORDER_TBL VALUES(222,'KEYBOARD',6,500,3),
(333,'USB',5,200,1),
(444,'RAM',6,900,2),
(555,'MOUSE',8,300,4),
(666,'MONITOR',6,500,5),
(777,'MOUSEPAD',2,60,6),
(888,'SCREENGUARD',1,600,4),
(999,'BUTTON',56,80,5),
(101,'POWER',5,900,3);



SELECT *  FROM REFERENTIAL_INTEGRITY.Customer_tbl;

SELECT *  FROM REFERENTIAL_INTEGRITY.ORDER_TBL;


DELETE FROM REFERENTIAL_INTEGRITY.Customer_tbl WHERE  C_ID=3;

Insert into REFERENTIAL_INTEGRITY.Customer_tbl Values
(3,'MANISH','SATARA','HYDERABAD');


DELETE FROM REFERENTIAL_INTEGRITY.ORDER_TBL WHERE  REFERENTIAL_INTEGRITY.ORDER_TBL.C_ID=3;

UPDATE REFERENTIAL_INTEGRITY.Customer_tbl
SET c_id=3 WHERE C_ID=6;


DELETE FROM REFERENTIAL_INTEGRITY.Customer_tbl WHERE  REFERENTIAL_INTEGRITY.Customer_tbl.C_ID=5;

TRUNCATE TABLE REFERENTIAL_INTEGRITY.Customer_tbl;

DROP TABLE REFERENTIAL_INTEGRITY.ORDER_tbl;


SELECT *  FROM REFERENTIAL_INTEGRITY.Customer_tbl;

SELECT *  FROM REFERENTIAL_INTEGRITY.ORDER_TBL;


Insert into REFERENTIAL_INTEGRITY.Customer_tbl Values(6,'MODI','SURAT','GUJRAT');

Insert into REFERENTIAL_INTEGRITY.ORDER_TBL Values(111,'KEYBOARD',56,688,6);
