-------------------------------------------------IDENTITY(START,INCREMENT)-------------------------------------------------

CREATE TABLE TEACHER_TBL(
T_ID INT PRIMARY KEY IDENTITY,
T_NAME VARCHAR(50),
T_QUALIFICATION VARCHAR(50),
T_SALARY INT
);


INSERT INTO TEACHER_TBL VALUES('NEERAJ','MBA',50000);

INSERT INTO TEACHER_TBL VALUES('PANKAJ','MCA',60000);

INSERT INTO TEACHER_TBL VALUES('ASHUTOSH','BSC-IT',30000);

INSERT INTO TEACHER_TBL VALUES('SACHIN','B.COM',20000);

INSERT INTO TEACHER_TBL VALUES('SHIV','BSC',10000);

SELECT * FROM TEACHER_TBL;


DROP TABLE TEACHER_TBL;


CREATE TABLE TEACHER_TBL(
T_ID INT PRIMARY KEY IDENTITY(2,2),
T_NAME VARCHAR(50),
T_QUALIFICATION VARCHAR(50),
T_SALARY INT
);



INSERT INTO TEACHER_TBL VALUES('NEERAJ','MBA',50000);

INSERT INTO TEACHER_TBL VALUES('PANKAJ','MCA',60000);

INSERT INTO TEACHER_TBL VALUES('ASHUTOSH','BSC-IT',30000);

INSERT INTO TEACHER_TBL VALUES('SACHIN','B.COM',20000);

INSERT INTO TEACHER_TBL VALUES('SHIV','BSC',10000);

SELECT * FROM TEACHER_TBL;


DROP TABLE TEACHER_TBL;


CREATE TABLE TEACHER_TBL(
T_ID INT PRIMARY KEY IDENTITY(0,100), ---IDENTITY(START,INCREMENT)
T_NAME VARCHAR(50),
T_QUALIFICATION VARCHAR(50),
T_SALARY INT
);


INSERT INTO TEACHER_TBL VALUES('NEERAJ','MBA',50000);

INSERT INTO TEACHER_TBL VALUES('PANKAJ','MCA',60000);

INSERT INTO TEACHER_TBL VALUES('ASHUTOSH','BSC-IT',30000);

INSERT INTO TEACHER_TBL VALUES('SACHIN','B.COM',20000);

INSERT INTO TEACHER_TBL VALUES('SHIV','BSC',10000);

SELECT * FROM TEACHER_TBL;



------------------------------------------------UNION & UNION ALL--------------------------------------------------------------------------


CREATE TABLE FOOTBALL_PARTICIPANTS(
FOOT_ID INT,
F_NAME VARCHAR(50),
EMAIL_ID VARCHAR(MAX),
);

INSERT INTO FOOTBALL_PARTICIPANTS VALUES(1,'NEERAJ GUPTA','NEERAJG123@GMAIL.COM');

INSERT INTO FOOTBALL_PARTICIPANTS VALUES(2,'SHIV GUPTA','SHIVG123@GMAIL.COM');

INSERT INTO FOOTBALL_PARTICIPANTS VALUES(3,'AMAN GUPTA','AMANG123@GMAIL.COM');

INSERT INTO FOOTBALL_PARTICIPANTS VALUES(4,'MANISH GUPTA','MANISHG123@GMAIL.COM');

INSERT INTO FOOTBALL_PARTICIPANTS VALUES(5,'PANKAJ GUPTA','PANKAJG123@GMAIL.COM');

CREATE TABLE HOCKEY_TBL(
H_ID INT,
H_NAME VARCHAR(50),
EMAIL_ID VARCHAR(MAX),
);


INSERT INTO HOCKEY_TBL VALUES(1,'NEERAJ GUPTA','NEERAJG123@GMAIL.COM');

INSERT INTO HOCKEY_TBL VALUES(2,'SHIV GUPTA','SHIVG123@GMAIL.COM');

INSERT INTO HOCKEY_TBL VALUES(3,'PRAKASH GUPTA','PRAKASHG123@GMAIL.COM');

INSERT INTO HOCKEY_TBL VALUES(4,'SUNNY GUPTA','SUNNYG123@GMAIL.COM');

INSERT INTO HOCKEY_TBL VALUES(5,'ARUN GUPTA','ARUNG123@GMAIL.COM');


SELECT * FROM HOCKEY_TBL;

SELECT * FROM FOOTBALL_PARTICIPANTS;

--------------------UNION ---------------

SELECT * FROM HOCKEY_TBL
UNION
SELECT * FROM FOOTBALL_PARTICIPANTS;

--------------------UNION ALL ---------------

SELECT * FROM HOCKEY_TBL
UNION ALL
SELECT * FROM FOOTBALL_PARTICIPANTS;


CREATE TABLE CRICKET_PARTICIPANTS(
C_ID INT,
C_NAME VARCHAR(50),
EMAIL_ID VARCHAR(MAX),
);


INSERT INTO CRICKET_PARTICIPANTS VALUES(1,'NEERAJ GUPTA','NEERAJG123@GMAIL.COM');

INSERT INTO CRICKET_PARTICIPANTS VALUES(2,'PANKAJ GUPTA','PANKAJG123@GMAIL.COM');

INSERT INTO CRICKET_PARTICIPANTS VALUES(3,'OM GUPTA','OMG123@GMAIL.COM');

INSERT INTO CRICKET_PARTICIPANTS VALUES(4,'ANIL GUPTA','ANILG123@GMAIL.COM');

INSERT INTO CRICKET_PARTICIPANTS VALUES(5,'AMIT GUPTA','AMITG123@GMAIL.COM');

SELECT * FROM HOCKEY_TBL;

SELECT * FROM FOOTBALL_PARTICIPANTS;

SELECT * FROM CRICKET_PARTICIPANTS;

--------------------UNION ---------------

SELECT * FROM HOCKEY_TBL
UNION
SELECT * FROM FOOTBALL_PARTICIPANTS
UNION
SELECT * FROM CRICKET_PARTICIPANTS;

--------------------UNION ALL ---------------

SELECT * FROM HOCKEY_TBL
UNION ALL
SELECT * FROM FOOTBALL_PARTICIPANTS
UNION ALL
SELECT * FROM CRICKET_PARTICIPANTS;


----------------------------------INTERSECT------------------------


SELECT * FROM HOCKEY_TBL
INTERSECT
SELECT * FROM FOOTBALL_PARTICIPANTS;



SELECT * FROM HOCKEY_TBL
INTERSECT
SELECT * FROM FOOTBALL_PARTICIPANTS
INTERSECT 
SELECT * FROM CRICKET_PARTICIPANTS;



--------------------------------------------EXCEPT----------------------------------------------

SELECT * FROM HOCKEY_TBL
EXCEPT
SELECT * FROM FOOTBALL_PARTICIPANTS;



SELECT * FROM HOCKEY_TBL
EXCEPT
SELECT * FROM FOOTBALL_PARTICIPANTS
EXCEPT 
SELECT * FROM CRICKET_PARTICIPANTS;