
-----------------------------------------------------SQL JOINS IN SQL--------------------------------------------------------------
CREATE SCHEMA JOINS;

CREATE TABLE JOINS.EMPLOYEE_TBL(
EMP_ID INT UNIQUE NOT NULL,
EMP_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(MAX) NOT NULL,
DESIGNATION VARCHAR(50) NOT NULL
);

INSERT INTO JOINS.EMPLOYEE_TBL VALUES(11,'NEERAJ','NEERAJG765@GMAIL.COM','MANAGER');
INSERT INTO JOINS.EMPLOYEE_TBL VALUES(22,'PANKAJ','PANKAJG765@GMAIL.COM','TEAM MEMBER');
INSERT INTO JOINS.EMPLOYEE_TBL VALUES(33,'DEEPAK','DEEPAKG765@GMAIL.COM','TEAM MEMBER');
INSERT INTO JOINS.EMPLOYEE_TBL VALUES(44,'ASHUTOSH','ASHUTOSHG765@GMAIL.COM','TEAM LEAD');
INSERT INTO JOINS.EMPLOYEE_TBL VALUES(55,'MANISH','MANISHG765@GMAIL.COM','TEAM MEMBER');
INSERT INTO JOINS.EMPLOYEE_TBL VALUES(66,'SATYA','SATYAG765@GMAIL.COM','TEAM MEMBER');


SELECT * FROM JOINS.EMPLOYEE_TBL;

CREATE TABLE JOINS.DEPARTMENT(
DEPT_ID INT UNIQUE NOT NULL,
DEPT_NAME VARCHAR(MAX) NOT NULL,
DEPT_SALARY INT NOT NULL,
EMP_ID INT UNIQUE NOT NULL
);

TRUNCATE TABLE JOINS.DEPARTMENT;

INSERT INTO JOINS.DEPARTMENT VALUES(111,'ADMIN',490000,11);
INSERT INTO JOINS.DEPARTMENT VALUES(222,'SECURITY',90000,22);
INSERT INTO JOINS.DEPARTMENT VALUES(333,'IS',40000,33);
INSERT INTO JOINS.DEPARTMENT VALUES(444,'FIANACE',4960000,44);
INSERT INTO JOINS.DEPARTMENT VALUES(555,'IT',980000,55);
INSERT INTO JOINS.DEPARTMENT VALUES(666,'HR',500000,77);

SELECT * FROM JOINS.EMPLOYEE_TBL;
SELECT * FROM JOINS.DEPARTMENT;

-----------------------------------------------------INNER JOIN IN SQL--------------------------------------------------------------

SELECT * FROM JOINS.EMPLOYEE_TBL AS A
INNER JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;



SELECT A.EMP_NAME,A.DESIGNATION,B.DEPT_NAME,B.DEPT_SALARY FROM JOINS.EMPLOYEE_TBL AS A
INNER JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;

-----------------------------------------------------LEFT JOIN IN SQL--------------------------------------------------------------


SELECT * FROM JOINS.EMPLOYEE_TBL AS A
LEFT JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;


SELECT A.DESIGNATION,A.EMP_NAME,B.DEPT_NAME,B.DEPT_SALARY FROM JOINS.EMPLOYEE_TBL AS A
LEFT JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;

SELECT * FROM JOINS.DEPARTMENT AS A
LEFT JOIN JOINS.EMPLOYEE_TBL AS B
ON A.EMP_ID = B.EMP_ID;


SELECT B.DESIGNATION,B.EMP_NAME,A.DEPT_NAME,A.DEPT_SALARY FROM JOINS.DEPARTMENT AS A
LEFT JOIN JOINS.EMPLOYEE_TBL AS B
ON A.EMP_ID = B.EMP_ID;

-----------------------------------------------------RIGHT JOIN IN SQL--------------------------------------------------------------


SELECT * FROM JOINS.EMPLOYEE_TBL AS A
RIGHT JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;


SELECT A.DESIGNATION,A.EMP_NAME,B.DEPT_NAME,B.DEPT_SALARY FROM JOINS.EMPLOYEE_TBL AS A
RIGHT JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;

SELECT * FROM JOINS.DEPARTMENT AS A
RIGHT JOIN JOINS.EMPLOYEE_TBL AS B
ON A.EMP_ID = B.EMP_ID;


SELECT B.DESIGNATION,B.EMP_NAME,A.DEPT_NAME,A.DEPT_SALARY FROM JOINS.DEPARTMENT AS A
RIGHT JOIN JOINS.EMPLOYEE_TBL AS B
ON A.EMP_ID = B.EMP_ID;


-----------------------------------------------------FULL JOIN IN SQL--------------------------------------------------------------



SELECT * FROM JOINS.EMPLOYEE_TBL AS A
FULL JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;



SELECT A.DESIGNATION,A.EMP_NAME,B.DEPT_NAME,B.DEPT_SALARY FROM JOINS.EMPLOYEE_TBL AS A
FULL JOIN JOINS.DEPARTMENT AS B
ON A.EMP_ID=B.EMP_ID;

-----------------------------------------------------SELF JOIN IN SQL--------------------------------------------------------------


CREATE TABLE SELFJOIN(
EMP_ID INT PRIMARY KEY ,
EMP_NAME VARCHAR(50),
MANAGER_ID INT
);


INSERT INTO SELFJOIN VALUES(1,'NEERAJ',4);
INSERT INTO SELFJOIN VALUES(2,'PANKAJ',4);
INSERT INTO SELFJOIN VALUES(3,'DEEPAK',5);
INSERT INTO SELFJOIN VALUES(4,'ASHUTOSH',6);
INSERT INTO SELFJOIN VALUES(5,'AVANI',1);
INSERT INTO SELFJOIN VALUES(6,'PRIYA',1);


SELECT * FROM SELFJOIN;

SELECT * FROM SELFJOIN AS A
INNER JOIN SELFJOIN AS B
ON A.EMP_ID= B.MANAGER_ID;

SELECT * FROM SELFJOIN;

SELECT B.EMP_NAME,A.EMP_NAME AS MANAGER_NAME FROM SELFJOIN AS A
INNER JOIN SELFJOIN AS B
ON A.EMP_ID= B.MANAGER_ID;
