-----------------------------------SELECT INTO STATEMENT-------------------------------------------------
SELECT * FROM EMPLOYEE;

SELECT * INTO NEW_EMPLOYEE FROM EMPLOYEE;

SELECT FirstName,LastName,Position,Salary INTO BACKUP_EMPLOYEE FROM EMPLOYEE;

SELECT * FROM NEW_EMPLOYEE;


SELECT * INTO EMPLOYEE_BACKUP FROM EMPLOYEE WHERE Position='MANAGER';

SELECT * FROM EMPLOYEE_BACKUP;

SELECT * INTO EMPLOYEE_JOIN_BACKUP FROM EMPLOYEE AS A
INNER JOIN Customer_tbl AS B
ON A.EmployeeID=B.c_id;

SELECT * FROM EMPLOYEE_JOIN_BACKUP;

SELECT A.FirstName,A.Position,A.Salary,B.c_address,B.city INTO EMPLOYEE_JOIN_BACKUP1 FROM EMPLOYEE AS A
INNER JOIN Customer_tbl AS B
ON A.EmployeeID=B.c_id;

SELECT * FROM EMPLOYEE_JOIN_BACKUP1;

SELECT * INTO SIT.DBO.EMPLOYEE_BACKUP_IN_NEW_DATABAE FROM Employee; -----------COPY TABLE DATA INSERT INTO OTHER DATABASE TABLE ALSO


SELECT * INTO EMPLOYEE_NEW_BACKUP FROM Employee WHERE 1<>1;

SELECT * FROM EMPLOYEE_NEW_BACKUP;

-----------------------------------INSERT INTO STATEMENT-------------------------------------------------

CREATE TABLE STUDENT_MUM_TBL(
S_ID INT,
S_NAME VARCHAR(50),
FATHER_NAME VARCHAR(50),
AGE INT,
CLASS INT);

INSERT INTO STUDENT_MUM_TBL VALUES(1,'PANKAJ','RAM',18,5),
(2,'NEERAJ','SHIV',15,9),
(3,'MANISH','SONU',17,8),
(4,'SIKANDER','SINGH',13,4),
(5,'PAWAN','KESHARI',12,7);

CREATE TABLE STUDENT_HYD_TBL(
STD_ID INT,
STD_NAME VARCHAR(50),
S_FATHER_NAME VARCHAR(50),
S_AGE INT,
S_CLASS INT);

INSERT INTO STUDENT_HYD_TBL VALUES(1,'PANKAJ','RAM',18,5),
(2,'AMEER','SHIVA',19,13);

SELECT * FROM STUDENT_HYD_TBL;
SELECT * FROM STUDENT_MUM_TBL;

INSERT INTO STUDENT_HYD_TBL SELECT * FROM STUDENT_MUM_TBL;


TRUNCATE TABLE STUDENT_HYD_TBL;
TRUNCATE TABLE STUDENT_MUM_TBL;


INSERT INTO STUDENT_HYD_TBL(STD_NAME,S_FATHER_NAME,S_AGE) 
SELECT S_NAME,FATHER_NAME,AGE FROM STUDENT_MUM_TBL;

SELECT * FROM STUDENT_HYD_TBL;
SELECT * FROM STUDENT_MUM_TBL;
