CREATE SCHEMA  SETDEFAULT;


Create Table SETDEFAULT.Customer_tbl(
c_id int primary key,
c_name varchar(50),
c_address varchar(50),
city varchar(50));



Insert into SETDEFAULT.Customer_tbl Values(1,'NEERAJ','KALYAN','MAHARASHTRA');

Insert into SETDEFAULT.Customer_tbl Values(2,'RAMESH','KALYAN','HYDERABAD'),
(3,'MANISH','SATARA','HYDERABAD'),
(4,'SATYANSH','KATIPURA','KOLKATA'),
(5,'VAIBHAV','KANPUR','UTTER PRADESH'),
(6,'AMAN','BANGOLARE','HYDERABAD');

CREATE  TABLE SETDEFAULT.ORDER_TBL(
ORD_ID INT PRIMARY KEY,
ITEM VARCHAR(50),
QUANTITY INT,
PRICE_OF_1 INT,
C_ID INT FOREIGN KEY REFERENCES SETDEFAULT.CUSTOMER_TBL(C_ID)
ON DELETE SET DEFAULT
ON UPDATE SET DEFAULT
);

INSERT INTO  SETDEFAULT.ORDER_TBL VALUES(222,'KEYBOARD',6,500,3),
(333,'USB',5,200,1),
(444,'RAM',6,900,2),
(555,'MOUSE',8,300,4),
(666,'MONITOR',6,500,5),
(777,'MOUSEPAD',2,60,6),
(888,'SCREENGUARD',1,600,4),
(999,'BUTTON',56,80,5),
(101,'POWER',5,900,3);


SELECT * FROM SETDEFAULT.Customer_tbl;

SELECT * FROM SETDEFAULT.ORDER_TBL;

ALTER TABLE SETDEFAULT.ORDER_TBL ADD DEFAULT 0 FOR C_ID;

INSERT INTO SETDEFAULT.Customer_tbl VALUES(0,'UNKNOWN','NO ADDRESS','NO CITY');

DELETE FROM SETDEFAULT.Customer_tbl WHERE C_ID = 6;

DELETE FROM SETDEFAULT.Customer_tbl WHERE C_ID = 3;

