
CREATE SCHEMA SETNULL;

Create Table SETNULL.Customer_tbl(
c_id int primary key,
c_name varchar(50),
c_address varchar(50),
city varchar(50));



Insert into SETNULL.Customer_tbl Values(1,'NEERAJ','KALYAN','MAHARASHTRA');

Insert into SETNULL.Customer_tbl Values(2,'RAMESH','KALYAN','HYDERABAD'),
(3,'MANISH','SATARA','HYDERABAD'),
(4,'SATYANSH','KATIPURA','KOLKATA'),
(5,'VAIBHAV','KANPUR','UTTER PRADESH'),
(6,'AMAN','BANGOLARE','HYDERABAD');


CREATE  TABLE SETNULL.ORDER_TBL(
ORD_ID INT PRIMARY KEY,
ITEM VARCHAR(50),
QUANTITY INT,
PRICE_OF_1 INT,
C_ID INT FOREIGN KEY REFERENCES SETNULL.CUSTOMER_TBL(C_ID)
ON DELETE SET NULL 
ON UPDATE SET NULL
);

INSERT INTO  SETNULL.ORDER_TBL VALUES(222,'KEYBOARD',6,500,3),
(333,'USB',5,200,1),
(444,'RAM',6,900,2),
(555,'MOUSE',8,300,4),
(666,'MONITOR',6,500,5),
(777,'MOUSEPAD',2,60,6),
(888,'SCREENGUARD',1,600,4),
(999,'BUTTON',56,80,5),
(101,'POWER',5,900,3);

DROP TABLE SETNULL.Customer_tbl;
DROP TABLE SETNULL.ORDER_TBL;

SELECT * FROM SETNULL.CUSTOMER_TBL;

SELECT * FROM SETNULL.ORDER_TBL;


DELETE FROM SETNULL.Customer_tbl WHERE C_ID=3;

UPDATE SETNULL.CUSTOMER_TBL
SET C_ID=3 WHERE C_ID=6;