

-----------------------------------store procedure----------------------------

select * from employee;


create procedure sp_getemployees
as 
begin 
select firstname,lastname,position ,Salary,HireDate from Employee
end;

sp_getemployees;---EXECUTION IN STORE PROCEDURE

exec sp_getemployees;---EXECUTION IN STORE PROCEDURE

execute sp_getemployees;---EXECUTION IN STORE PROCEDURE

-----------------------------------store procedure with SINGLE PARAMETERS----------------------------

CREATE PROCEDURE SP_GETEMPLOYEE_BY_ID
@ID INT
AS 
BEGIN
SELECT * FROM Employee WHERE EmployeeID=@ID;
END;


SP_GETEMPLOYEE_BY_ID 4;---EXECUTION IN STORE PROCEDURE

SP_GETEMPLOYEE_BY_ID 113;---EXECUTION IN STORE PROCEDURE

EXEC SP_GETEMPLOYEE_BY_ID 112;---EXECUTION IN STORE PROCEDURE

EXECUTE SP_GETEMPLOYEE_BY_ID 101;---EXECUTION IN STORE PROCEDURE


--------------------------------------STORE PROCEDURE WITH MULTIPLE PARAMETERS ----------------------------

CREATE PROCEDURE GETEMPLOYEE_MULTIPLE_PARAMETERS
@ID INT,
@NAME VARCHAR(50)
AS
BEGIN 
SELECT * FROM EMPLOYEE WHERE EmployeeID=@ID AND Position=@NAME;
END

GETEMPLOYEE_MULTIPLE_PARAMETERS 111,'DEVELOPER';---EXECUTION IN STORE PROCEDURE


ALTER PROCEDURE GETEMPLOYEE_MULTIPLE_PARAMETERS
@ID INT,
@POSITION_VALUE VARCHAR(50),
@NAME VARCHAR(50)
AS
BEGIN 
SELECT * FROM EMPLOYEE WHERE EmployeeID=@ID AND Position=@POSITION_VALUE AND FirstName=@NAME;
END

GETEMPLOYEE_MULTIPLE_PARAMETERS 118,'MANAGER','QUINN';---EXECUTION IN STORE PROCEDURE

--------------------------------------STORE PROCEDURE CODE SHOW WITH BUILT-IN PROCEDURE ----------------------------

SP_HELPTEXT GETEMPLOYEE_MULTIPLE_PARAMETERS;

--------------------------------------DROP STORE PROCEDURES  ----------------------------

DROP PROCEDURE sp_getemployees;

--------------------------------------WITH ENCRYPTION IN STORE PROCEDURES  ----------------------------

ALTER PROCEDURE GETEMPLOYEE_MULTIPLE_PARAMETERS
@ID INT,
@POSITION_VALUE VARCHAR(50),
@NAME VARCHAR(50)
WITH ENCRYPTION
AS
BEGIN 
SELECT * FROM EMPLOYEE WHERE EmployeeID=@ID AND Position=@POSITION_VALUE AND FirstName=@NAME;
END

GETEMPLOYEE_MULTIPLE_PARAMETERS 118,'MANAGER','QUINN'; ---EXECUTION IN STORE PROCEDURE


SP_HELPTEXT GETEMPLOYEE_MULTIPLE_PARAMETERS;---The text for object 'GETEMPLOYEE_MULTIPLE_PARAMETERS' is encrypted.



-----------------------------------------STORED PROCEDURE WITH OUTPUT PARAMETERS---------------------

ALTER PROC EMPLOYEE_COUNT_OUTPUT_PARAMETERS
@SALARY INT OUTPUT,
@POSTION VARCHAR(50)
AS 
BEGIN
SELECT @SALARY=SUM(SALARY) FROM EMPLOYEE WHERE Position=@POSTION;
END


DECLARE @TOTAL_SALARY INT
EXECUTE EMPLOYEE_COUNT_OUTPUT_PARAMETERS @TOTAL_SALARY OUTPUT ,'MANAGER';
SELECT @TOTAL_SALARY;


